# The default microservice configuration, security credentials should be
# set with enviroment variables, every key on this config has a env var
# equivalent that sets or overrides the config on this file.
#
# Commented properties on this file are sensitive and should be set only
# by the their env var equivalent, in development they can be hardcoded
# within the config.dev.yml file

app:
  debug: false                              # APP_DEBUG
  max_invalid_packets: 50                   # MAX_INVALID_PACKETS

rmq:
  # url:                                    # RMQ_URL
  exchange: "tracker_events_topic"          # RMQ_EXCHANGE
  reconnect_wait_time: 5                    # RMQ_RECONNECT_WAIT_TIME

tracer:
  url: "http://localhost:14268/api/traces"  # TRACER_URL
  service_name: "tracker_reciever"          # TRACER_SERVICE_NAME
